version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  mailhog:
    image: "mailhog/mailhog"
    logging:
      driver: 'none'
    ports:
      - "1025:1025"
      - "8025:8025"